language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shazi986/docker-react -f frontend/Dockerfile.dev

script:
  - docker run -e CI=true shaz986/docker-react npm run test -- --coverage