language: generic
sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t myimage -f Dockerfile.dev .

script:
  - docker run -e CI=true myimage npm run test -- --coverage