language: generic
sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t shazi986/docker-react -f Dockerfile.dev .
  - docker run -e CI=true shazi986/docker-react npm run test -- --coverage